services:
  typesense:
    image: 'typesense/typesense:26.0'
    ports:
      - '${FORWARD_TYPESENSE_PORT:-8108}:8108'
    environment:
      TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
      TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
      TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
    volumes:
      - './sail-typesense:/typesense-data'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:8108/health'
      retries: 5
      timeout: 7s
  app:
    container_name: app
    image: 'ghcr.io/devsarry/coolify-deploy:main'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - typesense
    volumes:
      - './storage:/var/www/html/storage'
      - './database:/var/www/html/database'
    environment:
      PHP_FPM_POOL_NAME: "app"
      AUTORUN_ENABLED: 'true'
      APP_NAME: '${APP_NAME}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_TIMEZONE: '${APP_TIMEZONE}'
      APP_URL: '${APP_URL}'
      APP_LOCALE: '${APP_LOCALE}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE}'
      APP_MAINTENANCE_DRIVER: '${APP_MAINTENANCE_DRIVER}'
      BCRYPT_ROUNDS: '${BCRYPT_ROUNDS}'
      LOG_CHANNEL: 'stderr'
      LOG_STACK: 'stack'
      LOG_DEPRECATIONS_CHANNEL: '${LOG_DEPRECATIONS_CHANNEL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      SESSION_DRIVER: '${SESSION_DRIVER}'
      SESSION_LIFETIME: '${SESSION_LIFETIME}'
      SESSION_ENCRYPT: '${SESSION_ENCRYPT}'
      SESSION_PATH: '${SESSION_PATH}'
      SESSION_DOMAIN: '${SESSION_DOMAIN}'
      BROADCAST_CONNECTION: '${BROADCAST_CONNECTION}'
      FILESYSTEM_DISK: '${FILESYSTEM_DISK}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-redis}'
      CACHE_STORE: '${CACHE_STORE}'
      CACHE_PREFIX: '${CACHE_PREFIX}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
      VITE_APP_NAME: '${APP_NAME}'
      TMDB_API_KEY: '${TMDB_API_KEY}'
      REDIS_HOST: 'redis'
      REDIS_CLIENT: 'phpredis'
      REDIS_PASSWORD: 'redispassword'
      REDIS_PORT: '6379'
      TYPESENSE_HOST: 'typesense'
      TYPESENSE_PORT: '${TYPESENSE_PORT:-8108}'
      TYPESENSE_PROTOCOL: '${TYPESENSE_PROTOCOL:-http}'
      TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'

  scout-queue:
    image: 'ghcr.io/devsarry/coolify-deploy:main'
    command: [ "php", "/var/www/html/artisan", "queue:work", "redis", "--queue=scout"]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    volumes:
      - './storage:/var/www/html/storage'
      - './database:/var/www/html/database'
    healthcheck:
      # This is our native healthcheck script for the queue
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
    depends_on:
      - redis
      - typesense
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      REDIS_HOST: 'redis'
      REDIS_CLIENT: 'phpredis'
      REDIS_PASSWORD: 'redispassword'
      REDIS_PORT: '6379'
      TYPESENSE_HOST: 'typesense'
      TYPESENSE_PORT: '${TYPESENSE_PORT:-8108}'
      TYPESENSE_PROTOCOL: '${TYPESENSE_PROTOCOL:-http}'
      TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'

  redis:
    image: redis:6
    command: "redis-server --appendonly yes --requirepass redispassword"


#  horizon:
#    image: 'ghcr.io/devsarry/coolify-deploy:main'
#    command: [ "php", "/var/www/html/artisan", "horizon" ]
#    volumes:
#      - ./storage:/var/www/html/storage
#    environment:
#      PHP_FPM_POOL_NAME: "app_horizon"


